Repository weechat/weechat, pull requests merged in 2018-10, with the labels that each got.

#1259 core: allow specifying buffer number/name for /buffer localvar
  src/core/wee-command.c
Labels: enhancement

#1265 core: update Japanese translations
  doc/ja/weechat_plugin_api.ja.adoc
  po/ja.po
Labels: translations

#1267 lua: mkdir API functions should return ERROR on error.
  src/plugins/lua/weechat-lua-api.c
Labels: bug
