Repository weechat/weechat, pull requests merged in 2018-03, with the labels that each got.

#1155 core: update Japanese translations
  doc/ja/weechat_faq.ja.adoc
  doc/ja/weechat_plugin_api.ja.adoc
  doc/ja/weechat_user.ja.adoc
  po/ja.po
Labels: translations

#1158 core: update Japanese translations
  doc/ja/cmdline_options.ja.adoc
  doc/ja/weechat.1.ja.adoc
  doc/ja/weechat_dev.ja.adoc
  po/ja.po
Labels: translations

#1163 Replace getdtablesize() with sysconf(_SC_OPEN_MAX)
  src/gui/curses/headless/main.c
Labels: bug

#1168 core: update Japanese translations
  doc/ja/weechat-headless.1.ja.adoc
  doc/ja/weechat.1.ja.adoc
  doc/ja/weechat_plugin_api.ja.adoc
  po/ja.po
Labels: translations

#1164 doc: use '-out' instead of shell redirection for openssl ecparam
  doc/de/weechat_user.de.adoc
  doc/en/weechat_user.en.adoc
  doc/fr/weechat_user.fr.adoc
  doc/it/weechat_user.it.adoc
  doc/ja/weechat_user.ja.adoc
  doc/pl/weechat_user.pl.adoc
Labels: doc

#1171 workaround/fix DCC get hangs
  src/plugins/xfer/xfer-config.c
  src/plugins/xfer/xfer-config.h
  src/plugins/xfer/xfer-dcc.c
  src/plugins/xfer/xfer.c
  src/plugins/xfer/xfer.h
Labels: bug
