Repository weechat/weechat, pull requests merged in 2018-07, with the labels that each got.

#1222 core: update Japanese translations
  doc/ja/weechat_faq.ja.adoc
  po/ja.po
Labels: translations

#1223 doc: update Japanese translations
  doc/ja/weechat_faq.ja.adoc
  doc/ja/weechat_user.ja.adoc
Labels: translations

#1225 gui: fix uncleared completion item (#1162)
  src/gui/gui-completion.c
Labels: bug

#1228 don't overwrite user installed GNU auto* files
  autogen.sh
Labels: enhancement
