Repository weechat/weechat, pull requests merged in 2019-05, with the labels that each got.

#1342 cmake: allow custom libdir (fix #1341)
  CMakeLists.txt
  config.h.cmake
  src/plugins/alias/CMakeLists.txt
  src/plugins/buflist/CMakeLists.txt
  src/plugins/charset/CMakeLists.txt
  src/plugins/exec/CMakeLists.txt
  src/plugins/fifo/CMakeLists.txt
  src/plugins/fset/CMakeLists.txt
  src/plugins/guile/CMakeLists.txt
  src/plugins/irc/CMakeLists.txt
  src/plugins/javascript/CMakeLists.txt
  src/plugins/logger/CMakeLists.txt
  src/plugins/lua/CMakeLists.txt
  src/plugins/perl/CMakeLists.txt
  src/plugins/php/CMakeLists.txt
  src/plugins/python/CMakeLists.txt
  src/plugins/relay/CMakeLists.txt
  src/plugins/ruby/CMakeLists.txt
  src/plugins/script/CMakeLists.txt
  src/plugins/spell/CMakeLists.txt
  src/plugins/tcl/CMakeLists.txt
  src/plugins/trigger/CMakeLists.txt
  src/plugins/xfer/CMakeLists.txt
Labels: bug

#1346 core: add detection for Ruby 2.6
  cmake/FindRuby.cmake
Labels: enhancement

#1349 core: update Japanese translations
  doc/ja/weechat_quickstart.ja.adoc
  doc/ja/weechat_scripting.ja.adoc
  doc/ja/weechat_user.ja.adoc
  po/ja.po
Labels: translations
