Repository weechat/weechat, pull requests merged in 2019-10, with the labels that each got.

#1409 doc: update German documentation
  doc/de/weechat_faq.de.adoc
Labels: doc

#1410 core: update German translations
  po/de.po
Labels: translations

#1413 Added introductory description of Logger masks
  doc/en/weechat_user.en.adoc
Labels: doc

#982 Add a desktop file
  CMakeLists.txt
  weechat.desktop
Labels: enhancement

#1416 irc: add server option ssl_password for SSL certificate private key password (issue #115)
  src/plugins/irc/irc-command.c
  src/plugins/irc/irc-config.c
  src/plugins/irc/irc-server.c
  src/plugins/irc/irc-server.h
Labels: enhancement
