Repository weechat/weechat, pull requests merged in 2022-12, with the labels that each got.

#1854 Update Serbian translation
  doc/sr/weechat_dev.sr.adoc
  doc/sr/weechat_faq.sr.adoc
  doc/sr/weechat_plugin_api.sr.adoc
  doc/sr/weechat_user.sr.adoc
  po/sr.po
Labels: translations

#1843 scripts: Send null values to config section callbacks
  doc/de/weechat_scripting.de.adoc
  doc/en/weechat_plugin_api.en.adoc
  doc/en/weechat_scripting.en.adoc
  doc/fr/weechat_plugin_api.fr.adoc
  doc/fr/weechat_scripting.fr.adoc
  doc/it/weechat_plugin_api.it.adoc
  doc/it/weechat_scripting.it.adoc
  doc/ja/weechat_plugin_api.ja.adoc
  doc/ja/weechat_scripting.ja.adoc
  doc/pl/weechat_scripting.pl.adoc
  doc/sr/weechat_plugin_api.sr.adoc
  doc/sr/weechat_scripting.sr.adoc
  src/plugins/guile/weechat-guile-api.c
  src/plugins/guile/weechat-guile.c
  src/plugins/javascript/weechat-js-api.cpp
  src/plugins/javascript/weechat-js.cpp
  src/plugins/lua/weechat-lua-api.c
  src/plugins/lua/weechat-lua.c
  src/plugins/perl/weechat-perl-api.c
  src/plugins/perl/weechat-perl.c
  src/plugins/php/weechat-php-api.c
  src/plugins/php/weechat-php.c
  src/plugins/python/weechat-python-api.c
  src/plugins/python/weechat-python.c
  src/plugins/python/weechat.pyi
  src/plugins/ruby/weechat-ruby-api.c
  src/plugins/ruby/weechat-ruby.c
  src/plugins/tcl/weechat-tcl-api.c
Labels: bug

#1859 cmake: add support of compiling with enchant-2 for the Spell checker plugin
  cmake/FindENCHANT.cmake
Labels: feature

#1842 doc/api: Fix return values for callback_read and python examples for config_new_section
  doc/en/weechat_plugin_api.en.adoc
  doc/fr/weechat_plugin_api.fr.adoc
  doc/it/weechat_plugin_api.it.adoc
  doc/ja/weechat_plugin_api.ja.adoc
  doc/sr/weechat_plugin_api.sr.adoc
  src/plugins/python/weechat.pyi
Labels: doc
